[workspace]
members = ["domain", "application", "infra", "interface", "bootstrap", "derive_macros"]
resolver = "2"

[workspace.dependencies]
serde = { version = "*", features = ["derive"] }
serde_json = "*"
thiserror = "*"
anyhow = "*"
tokio = { version = "*", features = ["full"] }
chrono = { version = "*", features = ["serde"] }
sqlx = { version = "*", features = [
  "postgres",
  "runtime-tokio",
  "macros",
  "migrate",
  "chrono",
] }
async-trait = "*"
dotenvy = "*"
tracing = "*"
tracing-subscriber = "*"
argon2 = "*"
jsonwebtoken = "8"
criterion = { version = "0.5", features = ["html_reports", "async_tokio"] }
mockall = "0.13"
proptest = "1"
