[package]
name = "api_rest_v2"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "*", features = ["derive"] }
serde_json = "*"
thiserror = "*"
tokio = { version = "*", features = ["full"] }
sqlx = { version = "*", features = ["postgres", "runtime-tokio", "macros"] }
async-trait = "*"
dotenvy = "*"