[package]
name = "api_rest_v2"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "*", features = ["derive"] }
serde_json = "*"
thiserror = "*"
tokio = { version = "*", features = ["full"] }
chrono = { version = "*", features = ["serde"] }
sqlx = { version = "*", features = [
  "postgres",
  "runtime-tokio",
  "macros",
  "chrono",
] }
async-trait = "*"
dotenvy = "*"
tracing = "*"
tracing-subscriber = "*"
argon2 = "*"
jsonwebtoken = "8"

[dev-dependencies]
sqlx = { version = "*", features = [
  "postgres",
  "runtime-tokio",
  "macros",
  "migrate",
  "chrono",
] }
