[package]
name = "domain"
version = "0.1.0"
edition = "2024"

# domain/Cargo.toml
[dependencies]
serde = { workspace = true }
async-trait = { workspace = true }
thiserror = { workspace = true }
chrono = { workspace = true }
mockall = { workspace = true }
derive_macros = { path = "../derive_macros" }

[dev-dependencies]
proptest = { workspace = true }